name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch

categories:
  - title: 🚀 Features
    labels:
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: ♻️ Refactor
    labels:
      - refactor
  - title: 📦 Other Changes
    labels:
      - chore
      - build
      - ci

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- Žiadne zmeny'

template: |
  ## Changes

  $CHANGES

include:
  commits: true

replacers:
  - search: '/^## Changes\n\n\* No changes$/m'
    replace: '## Changes\n\n* Update includes commits pushed directly to main.'
