name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch

include:
  commits: true

categories:
  - title: 🚀 Features
    labels:
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: ♻️ Refactor
    labels:
      - refactor
  - title: 📦 Other Changes
    labels:
      - chore
      - build
      - ci

template: |
  ## Changes

  $CHANGES
